### ISSUE TITLE
[Feature Request] can you prevent the close button from quitting the app?

### ISSUE THREAD

**Issue by AlJohri** [scriptspry/Saavn-Mac#1]
to be more consistent with Spotify and other mac apps, can you prevent the close button from actually quitting the app?

so if I press `Cmd-W` (the standard close tab shortcut), it would close the current Saavn window but continue playing the song

if I press `Cmd-Q`, it actually quicks Saavn

**Comment by AlJohri** [comment]
also, thanks a bunch for making this!

**Comment by scriptspry** [comment]
I haven't updated the download link with the new build. For now, compiling it yourself should work. Let me know if you need me to update it, will do it later.

**Comment by AlJohri** [comment]
thanks for the quick turn around! will try it out

**Comment by AlJohri** [comment]
I think that Cmd-W should hide the app similar to Spotify. Currently its a noop.

**Comment by AlJohri** [comment]
- Pressing the "X" button hides the app properly.
- Pressing Cmd-H or Cmd-M also does not hide or minimize the application.

**Comment by AlJohri** [comment]
- I also noticed while typing my password incorrectly, in an attempt to delete it and try again, Cmd-A didn't work to select all text in the input box. This is the window I'm referring to:

![screen shot 2016-12-08 at 8 49 50 am](https://cloud.githubusercontent.com/assets/2790092/21012296/52b9a63e-bd23-11e6-8d73-a810a40d2dd7.png)

**Comment by AlJohri** [comment]
happy to look into this stuff if you point me in the right direction

**Comment by scriptspry** [comment]
I've not noticed this, nice catch! Seems like this is a gotcha with electron as described [here](https://pracucci.com/atom-electron-enable-copy-and-paste.html).

**Comment by scriptspry** [comment]
This [link](https://github.com/bengotow/electron-sample-apps/blob/master/menus/main.js) seems more thorough.
