### ISSUE TITLE
Error During installation

### ISSUE THREAD

**Issue by kondapallivjagan** [scriptspry/Saavn-Mac#12]
> cp -r build/Saavn-darwin-x64/Saavn.app /Applications/Saavn.app

cp: build/Saavn-darwin-x64/Saavn.app: No such file or directory.

Build Directory is basically empty. Any help fixing why install is failing?

Here is the complete log

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/7.7.3/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'install' ]
2 info using npm@4.1.2
3 info using node@v7.7.3
4 verbose run-script [ 'preinstall', 'install', 'postinstall' ]
5 info lifecycle Saavn@0.0.2~preinstall: Saavn@0.0.2
6 silly lifecycle Saavn@0.0.2~preinstall: no script for preinstall, continuing
7 info lifecycle Saavn@0.0.2~install: Saavn@0.0.2
8 verbose lifecycle Saavn@0.0.2~install: unsafe-perm in lifecycle true
9 verbose lifecycle Saavn@0.0.2~install: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/userprofile/Downloads/Saavn-Mac-master/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Frameworks/Mono.framework/Versions/Current/Commands
10 verbose lifecycle Saavn@0.0.2~install: CWD: /Users/userprofile/Downloads/Saavn-Mac-master
11 silly lifecycle Saavn@0.0.2~install: Args: [ '-c',
11 silly lifecycle   'cp -r build/Saavn-darwin-x64/Saavn.app /Applications/Saavn.app' ]
12 silly lifecycle Saavn@0.0.2~install: Returned: code: 1  signal: null
13 info lifecycle Saavn@0.0.2~install: Failed to exec install script
14 verbose stack Error: Saavn@0.0.2 install: `cp -r build/Saavn-darwin-x64/Saavn.app /Applications/Saavn.app`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:194:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:194:7)
14 verbose stack     at maybeClose (internal/child_process.js:899:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid Saavn@0.0.2
16 verbose cwd /Users/userprofile/Downloads/Saavn-Mac-master
17 error Darwin 16.5.0
18 error argv "/usr/local/Cellar/node/7.7.3/bin/node" "/usr/local/bin/npm" "run" "install"
19 error node v7.7.3
20 error npm  v4.1.2
21 error code ELIFECYCLE
22 error Saavn@0.0.2 install: `cp -r build/Saavn-darwin-x64/Saavn.app /Applications/Saavn.app`
22 error Exit status 1
23 error Failed at the Saavn@0.0.2 install script 'cp -r build/Saavn-darwin-x64/Saavn.app /Applications/Saavn.app'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the Saavn package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     cp -r build/Saavn-darwin-x64/Saavn.app /Applications/Saavn.app
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs Saavn
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls Saavn
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by scriptspry** [comment]
You need to do:

    npm run clean
    npm run pack


before you can run:

    npm run install
