### ISSUE TITLE
Facebook login not working

### ISSUE THREAD

**Issue by architchandra** [scriptspry/Saavn-Mac#14]
I just get an empty window after trying to login through Facebook. Is this project being maintained anymore?

**Comment by scriptspry** [comment]
https://github.com/scriptspry/Saavn-Mac/issues/2#issuecomment-265527671

Please reopen if the suggested fix doesn't work for you.

**Comment by architchandra** [comment]
That fix did not work. :/

**Comment by architchandra** [comment]
Actually, ignore. I quit the app again and tried the same thing again and it worked. :)
