### ISSUE TITLE
l[Feature Support] Adding support for Play/Pause using Airpods

### ISSUE THREAD

**Issue by him229** [scriptspry/Saavn-Mac#17]
Can you look into adding support for Play/Pause support for macOS for airpods. Maybe there's an updated api for macOS?

**Comment by scriptspry** [comment]
Seems impossible :(

Not sure if it's changed now, but see:

https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/626#issuecomment-229860519
