### ISSUE TITLE
Issue with login with facebook

### ISSUE THREAD

**Issue by bharath1992** [scriptspry/Saavn-Mac#2]
The redirection to login is to default browser but after authorizing it does not redirect back to app to complete the login

**Comment by AlJohri** [comment]
This didn't work for me. It opened a separate blank white window and hung there.

**Comment by scriptspry** [comment]
Reposting the commit message:

> - There is some issue with facebook's login dialog popup window that
causes a blank popup after login with facebook. I tried to fix this with
out any success.
> - With this fix, the login should work by following a sequence of steps
noted in the point below. It's ugly as hell, but it works.
> - If you close the popup, go back to home screen by clicking on saavn
logo, click login again, click on login with facebook, close the empty
popup, you should be redirected back to home screen with your account
logged in.
> - This is some ugly shit. Why can't saavn release an app of their own
already? Why the hell are we having to muck with electron here?

**Comment by architchandra** [comment]
Did not work for me. Another blank screen opens.

**Comment by architchandra** [comment]
Still using the same workaround. Can I request that this be fixed once and for all? Thanks.
