### ISSUE TITLE
Update Request

### ISSUE THREAD

**Issue by AvinashDevina** [scriptspry/Saavn-Mac#26]
Hi,
Can you please update app to support new web interface. 
pause button is working, previous and next buttons are not working.
[https://www.jiosaavn.com/](https://www.jiosaavn.com/)

Thanks
Avi

**Comment by scriptspry** [comment]
No idea why the Next/Previous stopped working. Seems very random. Sometimes seems to work in dev mode. No time to debug this. Issued an update to upgrade packages.

**Comment by scriptspry** [comment]
See #25

**Comment by AvinashDevina** [comment]
Thanks for the Update.
