### ISSUE TITLE
something weird is going on with pictures

### ISSUE THREAD

**Issue by AlJohri** [scriptspry/Saavn-Mac#9]
sorry for all the issues, just trying to use the app while working and running into things...

I'm running into an issue where none of the images are loading and each click has slowed down considerably.

The app consistently looks like this for me: 
![screen shot 2016-12-08 at 10 19 25 am](https://cloud.githubusercontent.com/assets/2790092/21015404/d515d81c-bd2f-11e6-8941-92bc745132fa.png)

Can we add something like https://github.com/sindresorhus/electron-debug to get some debug information?

**Comment by AlJohri** [comment]
Seems to be an https issue. 
![screen shot 2016-12-08 at 12 48 16 pm](https://cloud.githubusercontent.com/assets/2790092/21020971/a10064b0-bd44-11e6-9d40-6ab8c3a7fb05.png)

**Comment by scriptspry** [comment]
should this even be fixed in the app? this seems to be a **serious** issue on saavn's end.

**Comment by AlJohri** [comment]
I think it has to do with electron because it doesn't happen during normal usage of Saavn. Do you find the same behavior? I fixed it in #10 by disabling web security.
